# Configuración de Spring Boot
spring.application.name=product-api

# Configuración de la base de datos H2
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar consola de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Configuración de Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.enabled=true

# Configuración de logging
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.com.pragma.productapi=DEBUG